### ISSUE TITLE
Diagnose why End2End tests are failing

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/NServiceBus.Azure#319] opened 2017-10-20 12:57 UTC
https://github.com/Particular/EndToEnd/pull/259

**Comment by SeanFeldman** [comment] 2017-10-23 14:10
- Not happening in Debug, only Release
- Happens erratically 
- The issue is within ASB SDK. When `MessageReceiver.Close()` is called, it tries to abandon prefetched messages, but the internal `SbmpChannel` is closed, and then it tries to reconnect using `ChannelFactory`, but the factory is disposed as well. And that's when the `ObjectDisposedException` is thrown. This is happening in the ASB Client 4.x

**Comment by SeanFeldman** [comment] 2017-10-24 16:52
Closed via https://github.com/Particular/NServiceBus.AzureServiceBus/commit/22b23c422c32e389ade2aacfd837c3df611efc3a

**Closed by SeanFeldman** 2017-10-24 16:52 UTC
Labels: State: In Progress
